# Generated by Django 2.0.6 on 2018-06-12 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_unloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='date_added',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
